### THEORY: Pandas Data Analysis Project

Pandas is an open-source Python library used for data manipulation, analysis, and cleaning. It provides powerful data structures such as Series (1D) and DataFrame (2D), which make handling structured data easy and efficient.

Objective

The main objective of a Pandas project is to:

Read and process data from different sources (CSV, Excel, JSON, etc.)
Clean and transform raw data into a usable format
Analyze patterns and relationships in data
Generate meaningful insights
Key Concepts Used
1. Data Structures
Series: One-dimensional labeled array
DataFrame: Two-dimensional table with rows and columns

These structures help in organizing and analyzing data effectively.

2. Data Loading

Pandas allows importing data using functions like:

read_csv()
read_excel()
read_json()

This helps in bringing real-world datasets into the program.

3. Data Cleaning

Raw data often contains errors such as:

Missing values
Duplicate records
Incorrect data types

Pandas provides methods like:

dropna()
fillna()
drop_duplicates()

Cleaning ensures accuracy and reliability of results.

4. Data Manipulation

Data can be modified using:

Filtering (df[df['column'] > value])
Sorting (sort_values())
Renaming columns
Adding or deleting columns

This step helps reshape data for better analysis.

5. Data Analysis

Pandas supports statistical operations such as:

Mean, median, mode
Sum, count
Grouping data (groupby())

This helps in identifying trends and patterns.

6. Data Visualization

Although Pandas has basic plotting, it is often used with libraries like:

Matplotlib
Seaborn

Visualization helps present insights clearly through graphs.

Applications of Pandas
Business data analysis
Financial data processing
Machine learning preprocessing
Data science projects
Conclusion

Pandas simplifies complex data operations and allows efficient analysis of large datasets. It is a fundamental tool in data science, enabling users to clean, manipulate, and analyze data effectively to make informed decisions.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("college_student_placement_dataset.csv")

In [3]:
df.head(10)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No
5,CLG0015,96,5.26,5.32,7,No,5,8,0,No
6,CLG0071,123,6.68,6.58,5,No,7,8,2,Yes
7,CLG0096,111,8.77,8.76,7,No,3,1,2,Yes
8,CLG0097,92,6.47,6.33,9,No,7,8,5,No
9,CLG0057,108,8.82,8.60,4,No,5,9,1,No

In [7]:
df.isnull().sum()

College_ID                0
IQ                        0
Prev_Sem_Result           0
CGPA                      0
Academic_Performance      0
Internship_Experience     0
Extra_Curricular_Score    0
Communication_Skills      0
Projects_Completed        0
Placement                 0
dtype: int64

In [8]:
df.tail()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
9995,CLG0021,119,8.41,8.29,4,No,1,8,0,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9997,CLG0066,89,6.08,6.25,3,Yes,3,9,5,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [9]:
df.describe()

,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Extra_Curricular_Score,Communication_Skills,Projects_Completed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,99.471800,7.535673,7.532379,5.546400,4.970900,5.561800,2.513400
std,15.053101,1.447519,1.470141,2.873477,3.160103,2.900866,1.715959
min,41.000000,5.000000,4.540000,1.000000,0.000000,1.000000,0.000000
25%,89.000000,6.290000,6.290000,3.000000,2.000000,3.000000,1.000000
50%,99.000000,7.560000,7.550000,6.000000,5.000000,6.000000,3.000000
75%,110.000000,8.790000,8.770000,8.000000,8.000000,8.000000,4.000000
max,158.000000,10.000000,10.460000,10.000000,10.000000,10.000000,5.000000

In [10]:
df.shape

(10000, 10)

In [11]:
df.columns

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='str')

In [13]:
df.sort_values(by="CGPA", ascending=False)

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
5999,CLG0076,82,9.99,10.46,1,No,6,7,1,No
4004,CLG0027,79,10.00,10.46,1,Yes,1,9,5,Yes
9769,CLG0065,73,9.98,10.45,6,No,2,8,1,No
2277,CLG0072,82,9.99,10.45,4,Yes,7,4,0,No
8418,CLG0010,91,9.97,10.44,7,No,1,3,5,No
...,...,...,...,...,...,...,...,...,...,...
4147,CLG0090,98,5.06,4.59,8,No,3,3,0,No
3332,CLG0005,123,5.02,4.58,3,Yes,2,9,5,Yes
8574,CLG0025,97,5.06,4.57,6,No,7,5,2,No
8835,CLG0017,99,5.01,4.56,5,Yes,0,9,4,No
9333,CLG0044,113,5.03,4.54,6,Yes,9,5,4,No

In [15]:
df.columns

Index(['College_ID', 'IQ', 'Prev_Sem_Result', 'CGPA', 'Academic_Performance',
       'Internship_Experience', 'Extra_Curricular_Score',
       'Communication_Skills', 'Projects_Completed', 'Placement'],
      dtype='str')

In [16]:
df.sort_values(by="CGPA", ascending=False).head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
5999,CLG0076,82,9.99,10.46,1,No,6,7,1,No
4004,CLG0027,79,10.00,10.46,1,Yes,1,9,5,Yes
9769,CLG0065,73,9.98,10.45,6,No,2,8,1,No
2277,CLG0072,82,9.99,10.45,4,Yes,7,4,0,No
8418,CLG0010,91,9.97,10.44,7,No,1,3,5,No

In [18]:
df[df["CGPA"] > 8.5]

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement
7,CLG0096,111,8.77,8.76,7,No,3,1,2,Yes
9,CLG0057,108,8.82,8.60,4,No,5,9,1,No
10,CLG0063,93,8.73,8.90,2,Yes,5,6,0,No
12,CLG0064,103,8.64,9.01,7,Yes,8,6,1,No
17,CLG0050,104,9.61,10.01,10,Yes,9,2,4,No
...,...,...,...,...,...,...,...,...,...,...
9985,CLG0052,94,9.27,9.37,6,No,10,2,0,No
9992,CLG0062,109,9.92,10.09,2,Yes,5,10,3,Yes
9996,CLG0098,70,9.25,9.34,7,No,0,7,2,No
9998,CLG0045,107,8.77,8.92,3,No,7,5,1,No
9999,CLG0060,109,9.41,9.77,8,No,3,5,5,No

In [19]:
df["Result"] = np.where(df["CGPA"] >= 6, "Pass", "Fail")

In [20]:
df.head()

,College_ID,IQ,Prev_Sem_Result,CGPA,Academic_Performance,Internship_Experience,Extra_Curricular_Score,Communication_Skills,Projects_Completed,Placement,Result
0,CLG0030,107,6.61,6.28,8,No,8,8,4,No,Pass
1,CLG0061,97,5.52,5.37,8,No,7,8,0,No,Fail
2,CLG0036,109,5.36,5.83,9,No,3,1,1,No,Fail
3,CLG0055,122,5.47,5.75,6,Yes,1,6,1,No,Fail
4,CLG0004,96,7.91,7.69,7,No,8,10,2,No,Pass